baseURL = "https://blog.hotseat.io/"
languageCode = "en-us"
title = "The Hotblog"

[Params]
Website = "https://hotseat.io"
Facebook = "https://www.facebook.com/hotseatio/"
Instagram = "#"
Twitter = "https://twitter.com/hotseatio"
Github = "https://github.com/hotseatio/"
Rss = "#"



[params]
hideMadeWithLine = true

[markup]
  [markup.highlight]
    lineNos = false
    style = "monokai"
    tabWidth = 2
    noClasses = false
